from pathlib import Path

from src.agent.sequence import sequence_tables, sequence_external_knowledge, sequence_questions
from src.agent.utils import json_save
from src.agent.llm import LLM


class Planner:
    def __init__(self, output_dir, model="gpt4", root_number=5, ratio=1):
        self.llm = LLM(method=model)
        self.output_dir = f"{output_dir}/questions/"

        self.number_of_initial_questions = root_number
        self.ratio = ratio

    def construct_initial_prompt(self, dfs, metadata, data_source, external_knowledges=None):
        output_format = {"code": "Python code without code syntax block"}
        output_format = str(output_format)
        dataset_title = metadata["dataset_title"]
        dataset_description = metadata["dataset_description"]
        publisher = metadata["publisher"]

        table_information = sequence_tables(dfs, metadata)

        if external_knowledges is not None:
            knowledge = sequence_external_knowledge(external_knowledges)

        prompt = f"""You are a top data analyst for the tabular data. Your final goal is to generate insights from the table. Insights should be led from the informative intermediate results (e.g. graph of data distribution, statistical values of certain columns, ranking, aggregated values). Therefore, you are required to generate a sequence of good questions invoking insightful observations. After answering these questions, the insights will be generated based on the intermediate QA pairs. Following is the rules to generate questions. 
- The number of questions is {self.number_of_initial_questions}.
- Each question is expected to consider the contexts produced by the previous questions.
- Format of questions are connected via vertical lines without adding redundant explanation before and after the question parts, specifically 'text1 | text2 | text3 | ...'. 
- If you refer to column names and cell values in the table, you should avoid use exact names by rephrasing them naturally without enclosing single/double quotes.
- Questions ask to provide not only text-based simple answer but also text-based complicated statistical information (e.g. correlation) and visualization (e.g. graph of data distribution, heatmap relationships among columns).
- Questions should specify the output format for each question, saying that 'Please provide as a line chart', 'Please answer as a numerical value', etc...

Following is table information.
## Table Information
Data Origin: {data_source}
Data publisher: {publisher}
Data source: {dataset_title}
Data source description: {dataset_description}
"""
        
        for t_info in table_information:
            prompt += f"{t_info}\n\n"

        if external_knowledges is not None:
            prompt += "Following is the external knowledge on the tabular information. Please use the knowledge to make the ID-like or ambiguous words clear.\n"
            prompt += knowledge
            
        return prompt
    
    def construct_followup_prompt(self, dfs, metadata, data_source, external_knowledges=None, qa_pairs=None, insights=None, iteration=1):
        output_format = [{"reference": "List of insight numbers (e.g. ['I_0_1', 'I_1_3'])", "question": "Question text"}, {"reference": "...", "question": "..."}]
        output_format = str(output_format)
        dataset_title = metadata.get("dataset_title") or metadata.get()
        dataset_description = metadata["dataset_description"]
        publisher = metadata["publisher"]

        table_information = sequence_tables(dfs, metadata)

        if external_knowledges is not None:
            knowledge = sequence_external_knowledge(external_knowledges)

        if len(qa_pairs) > 0:
            pairs = sequence_questions(qa_pairs)
            image_paths = []
        else:
            pairs = None
            image_paths = []

        number_of_questions = self.number_of_initial_questions * (self.ratio ** iteration)

        prompt = f"""You are a top data analyst for the tabular data. Your final goal is to generate insights from the table. Insights should be led from the informative intermediate results (e.g. graph of data distribution, statistical values of certain columns). Therefore, you are required to generate a sequence of good follow-up questions invoking insightful observations by referring to questions and insights generated in the previous steps. After answering these questions, the insights will be generated based on the intermediate QA pairs. Following is the rules to generate questions. 
- The number of questions is {number_of_questions}.
- Follow-up questions are generated by referring to the single or multiple insights, and you must include which insights are referred to in the output. Therefore, output format is {output_format} in the strict JSON format without markdown formatting and indentation. Please do not add additional explanation.
- It is encouraged to aggregate multiple insights to generate single follow-up question.
- Each insight composes of not only insight text but also the question numbers that the insight is generated from, so please also refer to these questions.
- Avoid duplication of questions by referring to the generated questions so far.
- If you refer to column names and cell values in the table, you should avoid use exact names by rephrasing them naturally without enclosing single/double quotes.
- Questions must include mixing text-based simple answer, text-based complicated statistical information (e.g. correlation) and visualization (e.g. graph of data distribution, heatmap relationships among columns).
- Questions should specify the output format for each question, saying that 'Please provide as a line chart', 'Please answer as a numerical value', etc...

## Questions so far
{pairs}

## Insights so far
{insights}

Following is table information.
## Table Information
Data Origin: {data_source}
Data publisher: {publisher}
Data source: {dataset_title}
Data source description: {dataset_description}
"""
        
        for t_info in table_information:
            prompt += f"{t_info}\n\n"

        if external_knowledges is not None:
            prompt += "Following is the external knowledge on the tabular information. Please use the knowledge to make the ID-like or ambiguous words clear.\n"
            prompt += knowledge

        print(prompt)
            
        return prompt, image_paths
    
    def _save_questions(self, questions, iteration):
        if not isinstance(questions, list):
            questions = questions.split("|")
        questions = {"questions": questions}

        Path(f"{self.output_dir}/iter{iteration}").mkdir(exist_ok=True, parents=True)
        output_path = f"{self.output_dir}/iter{iteration}/questions.json"
        json_save(output_path, questions)
    
    def followup(self, dfs, metadata, data_source, external_knowledge=None, qa_pairs=None, insights=None, iteration=0):
        prompt, image_paths = self.construct_followup_prompt(dfs, metadata, data_source, external_knowledge, qa_pairs=qa_pairs, insights=insights, iteration=iteration)
        if len(image_paths) == 0: image_paths = None

        questions = self.llm.generate_format(prompt, image_paths=image_paths, format='json')

        self._save_questions(questions, iteration)

        return questions
    
    def __call__(self, dfs, metadata, data_source, external_knowledge=None, iteration=0):
        prompt = self.construct_initial_prompt(dfs, metadata, data_source, external_knowledge)

        questions = self.llm(prompt)

        self._save_questions(questions, iteration)

        return questions